services:
  frontend:
    build:
      context: ./frontend
    ports:
      - 3000:3000
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    depends_on:
      - mongo
    expose: 
      - 3000

  mongo:
    image: mongo:4.2.0
    volumes:
      - ./data:/data/db
    expose:
      - 27017  

